### ISSUE TITLE
require(config.php) 

### ISSUE THREAD

**Issue by dotopidev** [chrismeller/cybersource#7]
i have installed it with in xxamp , when i go to http://localhost/cybersource/tests/main.php and i got this bug 
"Warning: require(config.php) [function.require]: failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/cybersource/tests/main.php on line 6"

I don't file any file named config.php in your souce ? so can you send me an example of this file ?

**Comment by chrismeller** [comment]
The class is instantiated in `main.php` with:

```
$c = CyberSource::factory( $merchant_id, $transaction_id, CyberSource::ENV_TEST );
```

So `config.php` should simply set `$merchant_id` and `$transaction_id`.

And you should not visit `main.php` directly, that won't do anything. You visit each of the "tests" separately.
