### ISSUE TITLE
Any plans to upgrade to the latest version of the SOAP API

### ISSUE THREAD

**Issue by abishekrsrikaanth** [chrismeller/cybersource#9]
Cybersource's latest version is @ 1.93. Are here any plans to upgrade this library to use the latest SOAP WSDL? 

https://ics2ws.ic3.com/commerce/1.x/transactionProcessor/

**Comment by chrismeller** [comment]
I didn't have any specific plans to, but they're _usually_ backwards compatible, so it wouldn't be difficult to update it. Is there something specific from the new version that you're looking for?

**Comment by abishekrsrikaanth** [comment]
Well, I just started integration with this library and noticed that it is quite a few versions below the current version. So was wondering if you will be updating anytime soon.

Also, I was wondering how I could send the credentials of the integration when integrating the same. 

I see on the doc that a config.php file needs to be created to read with the following information

```
<?php

$merchant_id = 'xxx';
$transaction_id = 'yyy';
$username = 'zzz';
$password = 'vvv';
```

but, if I had to use the factory directly or extended the library, how can i pass the credentials.

I was expecting the library to be able to send them on the constructor or the factory method.

```
public function __construct ( $merchant_id = null, $transaction_id = null, $environment = self::ENV_TEST, $username="", $password="") {

            $this->merchant_id( $merchant_id );
            $this->transaction_id( $transaction_id );

            $this->environment( $environment );

               if(empty($username)
                              //read from the config file

               if(empty($password)
                              //read from the config file           
        }
```

Is there a simpler way to do this?

**Comment by chrismeller** [comment]
The version of the WSDL is a bit misleading. In my experience the updates between versions have been very minor and usually involve adding new functionality. It's not as if there were bugs in a previous release, so you need to update immediately.

They provide [release notes](http://apps.cybersource.com/library/documentation/release_notes/WS_API_Release_Notes/html/wwhelp/wwhimpl/js/html/wwhelp.htm#href=cover.html), so you can see if anything important to you changes.

For the examples in the `tests` directory you'll need a `config.php` file like that, yes. It gets used in `main.php`, which also creates an instance of the class. When you start using it yourself, you'll have to pass in the authentication information directly, it will not read from any pre-configured file - most people are going to be using a library like this inside an existing framework, so there is no telling where configuration information would come from.

For an example of how you would pass the credentials, see `tests/main.php` or the Usage section of the readme.

I'm going to close this, feel free to comment some more if you have other questions.
